server {
  listen 80;
  client_max_body_size 110m;
  location / {
    proxy_pass http://app:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  location ~ ^/d/([0-9a-f-]+)/ {
    proxy_pass http://host.docker.internal:$deployment_port;
  }
}
